### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by AnnoyingTechnology** [chrisjhill/MVC#2]
This framework seems very slick, too bad there isn't more documentation than the README.

**Comment by chrisjhill** [comment]
I agree the documentation is a little sparse at the moment due to time restraints. The readme should give you a good head start, but is there anything in particular you needed help with?

Installing should only be a two minute job as you just need to checkout a copy of the source files and head over to your app's config in `/Library/MyProject/config.ini` and update the `path`'s to your specific directory structure.

**Comment by AnnoyingTechnology** [comment]
Thanks, at the time I wanted to see if it was worth developing my own framework or forking yours to modify it. 
I ended up doing something quite similar to your framework (I reused some of your classes).

https://github.com/SIB-FRANCE/Polyfony2
