### ISSUE TITLE
The router not work

### ISSUE THREAD

**Issue by ghost** [chrisjhill/MVC#5]
Hello,
i attempt to use your framework but the router it's as if it were not there. To prove I have passed the example shown in the readme

```php
// Global configurations
include dirname(__FILE__) . '/../Library/global.php';

// Create new Router instance
$router = new Core\Router();
$router
    ->addRoute('Foo')
    ->setRoute('foo/:bar/:acme')
    ->setFormat(array(
        'bar'  => '\d+',
        'acme' => '[a-z0-9]+')
    )
    ->setEndpoint(array(
        'controller' => 'Foo',
        'action'     => 'bar')
    );

// Start the application, passing in the Router
new Core\Front('MyProject', $router);
```

but by checking the contents of the variable `$route` we can see that it contains the most total nothingness.

```php
Core\Router Object
(
    [_routePath:Core\Router:private] => 
)
```

Some idea?

**Comment by chrisjhill** [comment]
Hi @adrix71,

What exactly are you trying to do and having problems with?

The reason your `print_r` is outputting that from the `$router` variable is because it does not output `static` properties which is where each route is placed.

*print_r(), var_dump() and var_export() will also show protected and private properties of objects. **Static class members will not be shown.***
 - http://php.net/manual/en/function.print-r.php

Hope that helps.

**Comment by ghost** [comment]
Hello chrisjhill. First and foremost thanks for response and sorry for my bad english.

True and sorry, I had not thought about static properties.

What I've tried is this

```php
$router
    ->addRoute('User')
    ->setRoute()
    ->setFormat()
    ->setEndpoint(array(
        'controller' => 'User',
        'action'     => 'welcome')
    );
```
and the User controller was done this way

```php
class User extends Controller
{
	/**
	 * The welcome action.
	 */
	public function welcomeAction()
    {
		$this->setLayout( 'user-welcome' );
	}
}
```
In Layout\user-welcome.php simple echo like:

```php
echo "Welcome from user controller";
```

but also to pass a `user/welcome` url always goes on the default page.

Thanks for helping.

**Comment by chrisjhill** [comment]
You are doing a few things slightly incorrectly:

1. You are using the MVC's "advanced" routing, but all you will probably need (from your example) is the simple routing:

    <?php
    // Global configurations
    include dirname(__FILE__) . '/../Library/global.php';
    // Start the application
    new Core\Front('MyProject');

However, if you did want to use the advanced routing then you need to change a couple things:

 - You need to add a "route", which is the URL that you navigate to.
 - You do not need the "format" option because you do not have any defined variables in the "route".

    $router = new Core\Router();
    $router
        ->addRoute('User')
        ->setRoute('user/welcome')
        ->setEndpoint(array(
            'controller' => 'User',
            'action'     => 'welcome')
        );

2. Your controller looks roughly right, however generally speaking you don't want to change the layout (the "header" and "footer"), you want to instead let it go through to the View Script. Let's assume you *do* want to change the layout - you'll need to make a `user-welcome.phtml` layout in the `Layout` directory (note the `phtml` extension, not `php`).

You'll then have to create your View Script (the "body") in `View/Script/User/Welcome.phtml`.

**Comment by ghost** [comment]
Wow work. Thanks

**Comment by chrisjhill** [comment]
That's great to hear.

I would really recommend re-reading the readme file (https://github.com/chrisjhill/MVC/blob/master/README.md) as it gives quite a bit of guidance on how the Controllers, Layouts, View Scripts, View Helpers, and View Partials fit together, and will answer *most* of any further questions.

Hope that helps.
